name: Build Plugin

on:
  push:
    branches: [main]
    paths-ignore: ['*.md']
  pull_request:
    branches: [main]
    paths-ignore: ['*.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      - name: Clone Aliucord
        run: |
          git clone --depth 1 https://github.com/Aliucord/Aliucord.git
          cd Aliucord
          git submodule update --init --recursive
          
      - name: Setup Plugin Directory
        run: |
          mkdir -p Aliucord/plugins/BetterBanners/src/main/kotlin/com/rhyans/betterbanner
          cp -r manifest.json build.gradle Aliucord/plugins/BetterBanners/
          cp -r src/main/kotlin/com/rhyans/betterbanner/BetterBanners.kt Aliucord/plugins/BetterBanners/src/main/kotlin/com/rhyans/betterbanner/
          
      - name: Build Plugin
        run: |
          cd Aliucord
          ./gradlew plugins:BetterBanners:build
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BetterBanners
          path: Aliucord/plugins/BetterBanners/build/outputs/plugin/*.zip
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Aliucord/plugins/BetterBanners/build/outputs/plugin/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
