name: Build BetterBanner Plugin

on:
  push:
    branches: [main]
    paths-ignore: ['*.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d cmdline-tools
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
          echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
          echo "$PWD/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          yes | sdkmanager --licenses >/dev/null 2>&1 || true
          sdkmanager "platform-tools" "platforms;android-33" >/dev/null 2>&1

      - name: Clone Aliucord
        run: |
          git clone --depth 1 https://github.com/Aliucord/Aliucord.git
          cd Aliucord
          git submodule update --init --recursive
          chmod +x gradlew

      - name: Install Plugin
        run: |
          PLUGIN_DIR="Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord"
          mkdir -p $PLUGIN_DIR/src/main/kotlin/com/rhyans/betterbanner
          cp -v build.gradle $PLUGIN_DIR/
          cp -v manifest.json $PLUGIN_DIR/
          cp -v src/main/kotlin/com/rhyans/betterbanner/BetterBanners.kt $PLUGIN_DIR/src/main/kotlin/com/rhyans/betterbanner/
          echo "include 'plugins:Sc-Rhyan57-betterBanner.aliucord'" >> Aliucord/settings.gradle

      - name: Build Plugin
        run: |
          cd Aliucord
          ./gradlew :plugins:Sc-Rhyan57-betterBanner.aliucord:build \
            --no-daemon \
            --stacktrace \
            -Dorg.gradle.jvmargs="-Xmx2g"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterBanner-Plugin
          path: Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/build/outputs/plugin/*.zip
