name: Build BetterBanner Plugin

on:
  push:
    branches: [main]
    paths-ignore: ['*.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools
          mkdir -p android-sdk/cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* android-sdk/cmdline-tools/latest/
          echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
          echo "$PWD/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          yes | sdkmanager --licenses >/dev/null 2>&1 || true
          sdkmanager "platform-tools" "platforms;android-33"

      - name: Build plugin
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterBanner-Plugin
          path: build/outputs/plugin/*.zip

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/outputs/plugin/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
