name: Build BetterBanner Plugin

on:
  push:
    branches: [main]
    paths-ignore: ['*.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK (Stable version)
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # Baixar versão estável compatível com JDK 11
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d cmdline-tools
          
          # Estrutura de pastas CORRIGIDA
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
          
          # Configurar environment
          echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
          echo "$PWD/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          
          # Aceitar licenças silenciosamente
          yes | sdkmanager --licenses >/dev/null 2>&1 || true
          sdkmanager "platform-tools" "platforms;android-33" >/dev/null

      - name: Verify Android SDK Installation
        run: |
          echo "=== Verificando estrutura de pastas ==="
          ls -la android-sdk/cmdline-tools/latest/bin/
          
          echo "=== Verificando sdkmanager ==="
          which sdkmanager || echo "sdkmanager não encontrado"
          
          echo "=== PATH atual ==="
          echo "$PATH"
          
          echo "=== Testando sdkmanager ==="
          sdkmanager --list || echo "Falha ao executar sdkmanager"

      - name: Build plugin
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterBanner-Plugin
          path: build/outputs/plugin/*.zip

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/outputs/plugin/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
