name: Build BetterBanner Plugin

on:
  push:
    branches: [main]
    paths-ignore: ['*.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Android Command Line Tools
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # Download stable version of command line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O cmdline-tools.zip
          
          # Create the proper directory structure required by Android tools
          mkdir -p android-sdk/cmdline-tools
          unzip -q cmdline-tools.zip -d android-sdk/cmdline-tools
          
          # Rename the extracted directory to follow the expected structure
          mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
          
          # Set environment variables
          echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PWD/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Accept Licenses
        run: |
          yes | ./android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses >/dev/null
          ./android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" >/dev/null

      - name: Clone Aliucord
        run: |
          git clone --depth 1 https://github.com/Aliucord/Aliucord.git
          cd Aliucord
          git submodule update --init --recursive
          chmod +x gradlew

      - name: Verify Source Files
        run: |
          echo "=== Project directory structure ==="
          ls -la
          
          echo "=== Source file paths ==="
          find . -name "*.gradle" -o -name "*.kt" -o -name "manifest.json"
          
          echo "=== Source file contents ==="
          echo "build.gradle:"
          cat build.gradle || echo "build.gradle not found"
          
          echo "manifest.json:"
          cat manifest.json || echo "manifest.json not found"
          
          echo "BetterBanners.kt:"
          cat src/main/kotlin/com/rhyans/betterbanner/BetterBanners.kt || echo "BetterBanners.kt not found"

      - name: Install Plugin
        run: |
          mkdir -p Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner
          cp -v build.gradle Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/
          cp -v manifest.json Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/
          cp -v src/main/kotlin/com/rhyans/betterbanner/BetterBanners.kt Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner/
          echo "include 'plugins:Sc-Rhyan57-betterBanner.aliucord'" >> Aliucord/settings.gradle
          
          echo "=== Plugin installation complete ==="
          echo "Checking plugin directory structure:"
          ls -la Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/
          
          echo "Checking settings.gradle:"
          cat Aliucord/settings.gradle

      - name: Build Plugin with Debug Output
        run: |
          cd Aliucord
          ./gradlew :plugins:Sc-Rhyan57-betterBanner.aliucord:build \
            --no-daemon \
            --info \
            --stacktrace \
            -Dorg.gradle.jvmargs="-Xmx2g"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterBanner-Plugin
          path: Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/build/outputs/plugin/*.zip
          if-no-files-found: warn
