name: Build BetterBanner Plugin

on:
  push:
    branches: [main]
    paths-ignore: ['*.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Android SDK
        run: |
          # Configuração inicial
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # Download da versão específica que funciona com JDK 11
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d cmdline-tools
          
          # Estrutura de pastas CORRETA (esta é a parte mais crítica)
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
          
          # Configuração do ambiente
          echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
          echo "$PWD/android-sdk/cmdline-tools/latest/bin:$PWD/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Verify SDK Installation
        run: |
          echo "=== Estrutura de pastas ==="
          ls -R android-sdk/cmdline-tools/
          
          echo "=== PATH atual ==="
          echo $PATH
          
          echo "=== Localização do sdkmanager ==="
          which sdkmanager || echo "sdkmanager não encontrado"
          
          echo "=== Versão do sdkmanager ==="
          sdkmanager --version || echo "Falha ao executar sdkmanager"

      - name: Accept licenses and install packages
        run: |
          yes | sdkmanager --licenses >/dev/null
          sdkmanager "platform-tools" "platforms;android-33" >/dev/null

      - name: Build plugin
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterBanner-Plugin
          path: build/outputs/plugin/*.zip
