name: Build BetterBanner Plugin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Android SDK (JDK 11 compatible)
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools/* android-sdk/cmdline-tools/latest/
        echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Prepare Aliucord
      run: |
        git clone --depth 1 https://github.com/Aliucord/Aliucord.git
        cd Aliucord
        git submodule update --init --recursive
        echo "org.gradle.daemon=false" >> gradle.properties
        chmod +x gradlew

    - name: Install Plugin Files
      run: |
        # Cria estrutura de diretórios
        mkdir -p Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner
        
        # Copia arquivos essenciais
        cp -v build.gradle Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/
        cp -v manifest.json Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/
        cp -v src/main/kotlin/com/rhyans/betterbanner/BetterBanners.kt Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner/
        
        # Atualiza settings.gradle
        echo "include 'plugins:Sc-Rhyan57-betterBanner.aliucord'" >> Aliucord/settings.gradle

    - name: Build Plugin
      run: |
        cd Aliucord
        ./gradlew :plugins:Sc-Rhyan57-betterBanner.aliucord:build \
          --no-daemon \
          --stacktrace \
          -Dorg.gradle.jvmargs="-Xmx2g"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BetterBanner-Plugin
        path: Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/build/outputs/plugin/*.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/build/outputs/plugin/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
