name: Build BetterBanner

on:
  push:
    branches: [main]
    paths-ignore: ['*.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK (Stable version)
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools
          mkdir -p android-sdk/cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* android-sdk/cmdline-tools/latest/
          echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
          echo "$PWD/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          yes | sdkmanager --licenses >/dev/null 2>&1 || true
          sdkmanager "platform-tools" "platforms;android-33"

      - name: Prepare Aliucord (with patched build)
        run: |
          git clone --depth 1 https://github.com/Aliucord/Aliucord.git
          cd Aliucord
          
          # Patch the build.gradle.kts to remove Android dependencies
          sed -i '/com.android.library/d' build.gradle.kts
          sed -i '/com.android.application/d' build.gradle.kts
          
          git submodule update --init --recursive
          chmod +x gradlew

      - name: Install Plugin
        run: |
          mkdir -p Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner
          cp -v build.gradle Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/
          cp -v manifest.json Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/
          cp -v src/main/kotlin/com/rhyans/betterbanner/BetterBanners.kt Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner/
          echo "include 'plugins:Sc-Rhyan57-betterBanner.aliucord'" >> Aliucord/settings.gradle

      - name: Build Plugin
        run: |
          cd Aliucord
          ./gradlew :plugins:Sc-Rhyan57-betterBanner.aliucord:build \
            --no-daemon \
            --stacktrace \
            -Dorg.gradle.jvmargs="-Xmx2g"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterBanner-Plugin
          path: Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/build/outputs/plugin/*.zip

      - name: Debug Aliucord Build
  run: |
    cd Aliucord
    ./gradlew :plugins:Sc-Rhyan57-betterBanner.aliucord:dependencies --no-daemon
