name: Build Plugin

on:
  push:
    branches: [main]
    paths-ignore: ['*.md']
  pull_request:
    branches: [main]
    paths-ignore: ['*.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configura o JDK 17 (necessário para o Android SDK)
      - name: Setup JDK 17
        id: setup-jdk-17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Configura o Android SDK (precisa do JDK 17)
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        env:
          SKIP_JDK_VERSION_CHECK: "true"  # Ignora a verificação de versão do JDK

      # 4. Configura o JDK 11 (necessário para o Aliucord)
      - name: Setup JDK 11
        id: setup-jdk-11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 5. Cache para acelerar builds futuros
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 6. Prepara o ambiente Aliucord
      - name: Preparar Aliucord
        run: |
          git clone --depth 1 https://github.com/Aliucord/Aliucord.git
          cd Aliucord
          git submodule update --init --recursive
          chmod +x gradlew

      # 7. Verifica se os arquivos necessários existem
      - name: Verificar arquivos
        run: |
          ls -la
          ls -la src/main/kotlin/com/rhyans/betterbanner/
          [ -f build.gradle ] || exit 1
          [ -f manifest.json ] || exit 1
          [ -f src/main/kotlin/com/rhyans/betterbanner/BetterBanners.kt ] || exit 1

      # 8. Instala o plugin na estrutura do Aliucord
      - name: Instalar Plugin
        run: |
          # Cria a estrutura de diretórios
          mkdir -p Aliucord/plugins/${{ github.repository_owner }}-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner
          
          # Copia os arquivos necessários
          cp -v build.gradle Aliucord/plugins/${{ github.repository_owner }}-betterBanner.aliucord/
          cp -v manifest.json Aliucord/plugins/${{ github.repository_owner }}-betterBanner.aliucord/
          cp -v src/main/kotlin/com/rhyans/betterbanner/BetterBanners.kt Aliucord/plugins/${{ github.repository_owner }}-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner/
          
          # Atualiza o settings.gradle
          echo "include 'plugins:${{ github.repository_owner }}-betterBanner.aliucord'" >> Aliucord/settings.gradle

      # 9. Constrói o plugin (usando JDK 11)
      - name: Construir Plugin
        run: |
          cd Aliucord
          ./gradlew :plugins:${{ github.repository_owner }}-betterBanner.aliucord:build --stacktrace

      # 10. Faz upload do artefato (plugin construído)
      - name: Upload do Plugin
        uses: actions/upload-artifact@v4
        with:
          name: betterBanner.aliucord
          path: Aliucord/plugins/${{ github.repository_owner }}-betterBanner.aliucord/build/outputs/plugin/*.zip

      # 11. Cria uma release automaticamente se for uma tag
      - name: Criar Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Aliucord/plugins/${{ github.repository_owner }}-betterBanner.aliucord/build/outputs/plugin/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
