name: Build BetterBanner Plugin

on:
  push:
    branches: [main]
    paths-ignore: ['*.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      # Use the official Android setup action instead of manual setup
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-33'

      - name: Clone Aliucord
        run: |
          git clone --depth 1 https://github.com/Aliucord/Aliucord.git
          cd Aliucord
          git submodule update --init --recursive
          chmod +x gradlew

      # Check Aliucord build environment
      - name: Debug Aliucord build environment
        run: |
          cd Aliucord
          cat build.gradle.kts || echo "build.gradle.kts not found"
          cat settings.gradle || cat settings.gradle.kts || echo "settings.gradle not found"
          
          # Create repositories.gradle if it doesn't exist
          echo "Adding Google Maven repository to repositories"
          cat > repositories.gradle << EOF
          repositories {
              google()
              mavenCentral()
              maven { url 'https://jitpack.io' }
          }
          
          buildscript {
              repositories {
                  google()
                  mavenCentral()
                  gradlePluginPortal()
              }
          }
          EOF
          
          # Add init script to include repositories
          mkdir -p ~/.gradle
          cat > ~/.gradle/init.gradle << EOF
          allprojects {
              buildscript {
                  repositories {
                      google()
                      mavenCentral()
                      gradlePluginPortal()
                  }
              }
              repositories {
                  google()
                  mavenCentral()
                  maven { url "https://jitpack.io" }
              }
          }
          EOF

      # Check for BetterBannerSettings.kt file
      - name: Check for Settings File
        id: check_settings
        run: |
          if [ -f "src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt" ]; then
            echo "settings_file_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "settings_file_exists=false" >> "$GITHUB_OUTPUT"
            echo "// Placeholder settings file for BetterBanner plugin" > src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "package com.rhyans.betterbanner" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "import android.content.Context" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "import android.view.View" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "import com.aliucord.PluginManager" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "import com.aliucord.Utils" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "import com.aliucord.api.SettingsAPI" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "import com.aliucord.views.Button" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "import com.aliucord.views.TextInput" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "class BetterBannerSettings(private val apiUrl: String) : com.aliucord.settings.SettingsPage() {" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "    override fun onViewCreated(view: View, savedInstanceState: android.os.Bundle?) {" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "        super.onViewCreated(view, savedInstanceState)" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "        val context = requireContext()" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "        val infoText = android.widget.TextView(context).apply {" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "            text = \"BetterBanners v1.0.0\\nPermite usar banners personalizados!\"" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "            textSize = 16f" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "            setPadding(0, 20, 0, 20)" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "        }" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "        addView(infoText)" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "    }" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
            echo "}" >> src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt
          fi

      - name: Install Plugin
        run: |
          mkdir -p Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner
          cp -v build.gradle Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/
          cp -v manifest.json Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/
          cp -v src/main/kotlin/com/rhyans/betterbanner/BetterBanners.kt Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner/
          cp -v src/main/kotlin/com/rhyans/betterbanner/BetterBannerSettings.kt Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/src/main/kotlin/com/rhyans/betterbanner/
          
          echo "include 'plugins:Sc-Rhyan57-betterBanner.aliucord'" >> Aliucord/settings.gradle
          
          echo "=== Plugin installation complete ==="
          echo "Checking plugin directory structure:"
          ls -la Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/
          
          echo "Checking settings.gradle:"
          cat Aliucord/settings.gradle

      - name: Build Plugin with Debug Output
        run: |
          cd Aliucord
          # Try building with more memory and debugging options
          GRADLE_OPTS="-Xmx4g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError" \
          ./gradlew :plugins:Sc-Rhyan57-betterBanner.aliucord:build \
            --no-daemon \
            --info \
            --stacktrace \
            -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=2g" \
            -Dandroid.useAndroidX=true \
            -Dandroid.enableJetifier=true \
            --scan

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterBanner-Plugin
          path: Aliucord/plugins/Sc-Rhyan57-betterBanner.aliucord/build/outputs/plugin/*.zip
          if-no-files-found: warn
